export const words = [
    "builders",
    "community",
    "students",
    "collaborators",
    "designers",
    "Ascend",
    "creators",
    "developers",
    "innovators",
    "consultants",
    "creatives",
    "coders",

    "builders",
    "community",
    "students",
    "collaborators",
    "designers",
    "Ascend",
    "creators",
    "developers",
    "innovators",
    "consultants",
    "creatives",
    "coders",

    "builders",
    "community",
    "students",
    "collaborators",
    "designers",
    "Ascend",
    "creators",
    "developers",
    "innovators",
    "consultants",
    "creatives",
    "coders",

    "builders",
    "community",
    "students",
    "collaborators",
    "designers",
    "Ascend",
    "creators",
    "developers",
    "innovators",
    "consultants",
    "creatives",
    "coders",

    "builders",
    "community",
    "students",
    "collaborators",
    "designers",
    "Ascend",
    "creators",
    "developers",
    "innovators",
    "consultants",
    "creatives",
    "coders",

];